### ISSUE TITLE
Implement _standardize_field_name() in pure C

### ISSUE THREAD

**Issue by xsawyerx** [p5pclub/http-headers-fast-xs#1]
`_standardize_field_name` is used all over the place. Unfortunately when it's in XS we can't access from other XS functions without going through the Perl stack, which is slow.

One way to solve it would be to implement the core of it in pure C without Perl-specific code. The main problem to contend with in order to do this is the caching. However, considering the C code is very fast, it might be worth it to remove the caching layer and normalize all the time.

We should benchmark first, to make sure.

**Comment by tsee** [comment]
Also, it's trivial to cache in C. :)

**Comment by xsawyerx** [comment]
Funny enough, running some benchmarks with `Dumbbench`, I can see that without the cache is faster. I can only (reasonably) assume that the normalization is faster than looking up HVs.

Done: https://github.com/p5pclub/http-headers-fast-xs/commit/3077b746aeacece3388596e45c9d7d5d0883bf80
